### ISSUE TITLE
Can't continue do_tokenize.py

### ISSUE THREAD

**Issue by Eunmul** [Ramprasad-Group/polyBERT#2]
Hi! I'm trying to train polyBERT from scratch what you described, but I can't run the `poetry run python do_tokenize.py`
If I run,
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Using custom data configuration default-ad1626d773764ba7
```
came out. I've tried to change data using
```
pip install zenodo-get
mkdir polyOne && cd polyOne
zenodo_get 7124188
```
but it just changed `ad1626d773764ba7` this number.

I've done all you described in README.md but this is what happened can you help me?..

**Comment by kuelumbus** [comment]
The warning by the tokenizer is not related to obtaining the data set from zenodo. You can ignore the warning by the tokenizer. Please follow the instruction in the README at "Train polyBERT from scratch".

**Comment by Eunmul** [comment]
I've done with every previous tasks. `poetry run python train_tokenizer.py ` works well and at the next step it happened :(

**Comment by kuelumbus** [comment]
This is not an error. Training such models  might be very slow depending on your available hardware.

**Comment by Eunmul** [comment]
Oh ok thanks! I'll wait for the result!

**Comment by Eunmul** [comment]
I've solved it by not using poetry, just installing dependencies!
