### ISSUE TITLE
Encountered "module not found error" while running do_tokenizer.py

### ISSUE THREAD

**Issue by madhubantimukherjee** [Ramprasad-Group/polyBERT#3]
Hi Chris, we are trying to install and train polyBERT from scratch in our local server. Followed the instructions given in README. The following error comes: (see the attached)

![image](https://github.com/Ramprasad-Group/polyBERT/assets/31185879/582dd5f2-c667-4b17-a087-5e9281defd16)

Please let us know how to fix it. Thanks!

**Comment by kuelumbus** [comment]
Hi. This error might indicate that you are missing the xz library on the system. You would need to install it before running the tokenizer. Also, there is no need to run `poetry` using `sudo`. This might also cause some issues.

**Comment by kuelumbus** [comment]
Closing this because no response. Please feel free to reopen.
