### ISSUE TITLE
Sample script to use SentenceTransformer on a locally trained model

### ISSUE THREAD

**Issue by enricogandini** [Ramprasad-Group/polyBERT#5]
Thanks for providing scripts to train the polyBERT tokenizer and transformer from scratch!

The paper mentions that you used SentenceTransformer to calculate the fingerprints.
Could you please provide a script that uses SentenceTransformer on a locally trained polyBERT transformer?
Basically, this script should take as input the output of the `train_transformer.py` script, build a SentenceTransformer model from it, and compute the fingerprints.

On [HuggingFace](https://huggingface.co/kuelumbus/polyBERT), you explain how to use SentenceTransformer to compute fingerprints for the the version of polyBERT that you trained and deployed on HuggingFace.
But I would also like to use SentenceTransformer on a locally trained model.

**Comment by kuelumbus** [comment]
Hi. Please see the documentation of SentenceTransformer at https://www.sbert.net/ for using SentenceTransformer for your own model.
